import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const p = await b.newPage();
p.on("response", (r) => { if (r.request().method() === "POST") console.log("POST", r.url(), r.status(), JSON.stringify(r.headers()["set-cookie"] ?? null).slice(0,200)); });
await p.goto("http://localhost:3000/", { waitUntil: "networkidle" });
console.log("before:", await p.getAttribute("html", "dir"));
await p.locator("header").getByRole("link").first().click();
await p.waitForLoadState("networkidle");
console.log("after:", await p.getAttribute("html", "dir"), p.url());
console.log("cookies:", (await p.context().cookies()).map(c => `${c.name}=${c.value}`).join(", "));
await b.close();
