import { bank } from "./shared";

export const mathBank = bank("math", [
  {
    id: "number",
    title: "Numbers and Place Value|الأعداد والقيمة المكانية",
    summary:
      "Reading, writing, comparing and ordering numbers, and understanding what each digit is worth.|قراءة الأعداد وكتابتها ومقارنتها وترتيبها، وفهم قيمة كل رقم في العدد.",
    topics: {
      early: [
        "Counting objects to 10|العدّ حتى ١٠",
        "Recognising and writing numerals|تمييز الأرقام وكتابتها",
        "More, fewer and the same|أكبر وأصغر ويساوي",
        "Counting to 20 and beyond|العدّ حتى ٢٠ وما بعدها",
      ],
      lower: [
        "Numbers to 100|الأعداد حتى ١٠٠",
        "Tens and ones|العشرات والآحاد",
        "Comparing numbers with < > =|مقارنة الأعداد باستخدام < > =",
        "Numbers to 1000|الأعداد حتى ١٠٠٠",
        "Skip counting by 2s, 5s and 10s|العدّ القفزي بـ٢ و٥ و١٠",
        "Even and odd numbers|الأعداد الزوجية والفردية",
      ],
      middle: [
        "Place value to 10,000|القيمة المكانية حتى ١٠٠٠٠",
        "Rounding to the nearest ten and hundred|التقريب لأقرب عشرة ومئة",
        "Comparing and ordering large numbers|مقارنة الأعداد الكبيرة وترتيبها",
        "Place value to millions|القيمة المكانية حتى الملايين",
        "Rounding to any place|التقريب لأي منزلة",
        "Writing numbers in expanded form|كتابة العدد بالصيغة التحليلية",
        "Powers of ten|قوى العشرة",
        "Decimal place value|القيمة المكانية للأعداد العشرية",
        "Ordering decimals|ترتيب الأعداد العشرية",
      ],
      upper: [
        "Integers and the number line|الأعداد الصحيحة وخط الأعداد",
        "Absolute value and opposites|القيمة المطلقة والأعداد المتقابلة",
        "Ratios and unit rates|النسب والمعدلات",
        "Percentages of a quantity|النسبة المئوية من كمية",
        "Operations with rational numbers|العمليات على الأعداد النسبية",
        "Proportional relationships|العلاقات التناسبية",
        "Exponents and square roots|الأسس والجذور",
        "Scientific notation|الصيغة العلمية",
        "Percent increase and decrease|الزيادة والنقصان المئوي",
        "Rational and irrational numbers|الأعداد النسبية وغير النسبية",
        "Estimation and rounding in context|التقدير والتقريب في مسائل واقعية",
        "Simple and compound interest|الفائدة البسيطة والمركبة",
      ],
    },
  },
  {
    id: "operations",
    title: "Operations and Algebraic Thinking|العمليات والتفكير الجبري",
    summary:
      "Adding, subtracting, multiplying and dividing with understanding, then moving into algebra.|الجمع والطرح والضرب والقسمة بفهم، ثم الانتقال إلى الجبر.",
    topics: {
      early: [
        "Adding with objects up to 5|الجمع باستخدام الأشياء حتى ٥",
        "Taking away up to 5|الطرح حتى ٥",
        "Making 10|تكوين العدد ١٠",
      ],
      lower: [
        "Addition facts within 20|حقائق الجمع ضمن ٢٠",
        "Subtraction facts within 20|حقائق الطرح ضمن ٢٠",
        "Addition and subtraction word problems|المسائل الكلامية على الجمع والطرح",
        "Two-digit addition with regrouping|جمع عددين من منزلتين مع إعادة التجميع",
        "Two-digit subtraction with regrouping|طرح عددين من منزلتين مع إعادة التجميع",
        "Multiplication as equal groups|الضرب كمجموعات متساوية",
      ],
      middle: [
        "Multiplication facts to 10|حقائق الضرب حتى ١٠",
        "Division as sharing and grouping|القسمة كتوزيع وتجميع",
        "Multiplication and division word problems|المسائل الكلامية على الضرب والقسمة",
        "Multi-digit multiplication|ضرب الأعداد متعددة المنازل",
        "Long division with remainders|القسمة المطولة مع باقٍ",
        "Factors, multiples and prime numbers|العوامل والمضاعفات والأعداد الأولية",
        "Multiplying large numbers efficiently|ضرب الأعداد الكبيرة بطرق مختصرة",
        "Dividing by two-digit divisors|القسمة على عدد من منزلتين",
        "Order of operations|ترتيب العمليات",
      ],
      upper: [
        "Writing algebraic expressions|كتابة العبارات الجبرية",
        "Solving one-step equations|حل المعادلات ذات الخطوة الواحدة",
        "Solving two-step equations|حل المعادلات ذات الخطوتين",
        "Inequalities and their graphs|المتباينات وتمثيلها بيانيًا",
        "Linear equations and slope|المعادلات الخطية والميل",
        "Expanding and factorising expressions|فك الأقواس وتحليل العبارات",
        "Simultaneous equations|المعادلات الآنية",
        "Sequences and the nth term|المتتابعات والحد النوني",
        "Quadratic expressions|العبارات التربيعية",
        "Functions and function notation|الدوال وترميز الدالة",
        "Algebraic fractions|الكسور الجبرية",
        "Modelling with equations|النمذجة بالمعادلات",
      ],
    },
  },
  {
    id: "fractions",
    title: "Fractions and Decimals|الكسور والأعداد العشرية",
    summary:
      "Parts of a whole, equivalence, and calculating with fractions, decimals and percents.|أجزاء الكل والتكافؤ والحساب بالكسور والأعداد العشرية والنسب المئوية.",
    topics: {
      early: ["Halves of a shape|نصف الشكل", "Equal and unequal parts|الأجزاء المتساوية وغير المتساوية"],
      lower: [
        "Halves and quarters|الأنصاف والأرباع",
        "Equal shares of a whole|تقسيم الكل إلى أجزاء متساوية",
        "Fractions of a set|كسر من مجموعة",
        "Comparing simple fractions|مقارنة الكسور البسيطة",
      ],
      middle: [
        "Fractions on a number line|الكسور على خط الأعداد",
        "Equivalent fractions|الكسور المتكافئة",
        "Comparing fractions|مقارنة الكسور",
        "Adding and subtracting like fractions|جمع وطرح الكسور المتشابهة",
        "Tenths and hundredths as decimals|الأعشار والأجزاء من مئة",
        "Mixed numbers and improper fractions|الأعداد الكسرية والكسور غير الفعلية",
        "Adding fractions with unlike denominators|جمع الكسور المختلفة المقامات",
        "Multiplying fractions|ضرب الكسور",
        "Multiplying and dividing decimals|ضرب وقسمة الأعداد العشرية",
      ],
    },
  },
  {
    id: "geometry",
    title: "Geometry and Measurement|الهندسة والقياس",
    summary:
      "Shapes, angles, position, and measuring length, area, volume, time and money.|الأشكال والزوايا والموقع، وقياس الطول والمساحة والحجم والزمن والنقود.",
    topics: {
      early: [
        "Flat shapes around us|الأشكال المستوية حولنا",
        "Position words: above, below, beside|كلمات الموقع: فوق وتحت وبجانب",
        "Sorting by size and colour|التصنيف حسب الحجم واللون",
        "Repeating patterns|الأنماط المتكررة",
      ],
      lower: [
        "2D and 3D shapes|الأشكال ثنائية وثلاثية الأبعاد",
        "Measuring length with units|قياس الطول بوحدات",
        "Telling time to the hour and half hour|قراءة الساعة بالساعات والأنصاف",
        "Money: coins and notes|النقود: العملات والأوراق",
        "Measuring in centimetres and metres|القياس بالسنتيمتر والمتر",
        "Time to five minutes|قراءة الوقت لأقرب خمس دقائق",
      ],
      middle: [
        "Perimeter of shapes|محيط الأشكال",
        "Area by tiling unit squares|المساحة بعدّ المربعات",
        "Classifying quadrilaterals|تصنيف الأشكال الرباعية",
        "Angles and the protractor|الزوايا والمنقلة",
        "Lines of symmetry|محاور التماثل",
        "Area and perimeter formulas|قوانين المساحة والمحيط",
        "Volume of rectangular prisms|حجم المنشور المستطيلي",
        "The coordinate plane|المستوى الإحداثي",
        "Converting units of measure|تحويل وحدات القياس",
      ],
      upper: [
        "Angles in parallel lines|الزوايا بين المستقيمين المتوازيين",
        "Area and circumference of circles|مساحة الدائرة ومحيطها",
        "Surface area and volume of prisms|المساحة السطحية وحجم المنشورات",
        "The Pythagorean theorem|نظرية فيثاغورس",
        "Transformations of shapes|تحويلات الأشكال",
        "Similar and congruent figures|الأشكال المتشابهة والمتطابقة",
        "Trigonometric ratios|النسب المثلثية",
        "Volume of cylinders, cones and spheres|حجم الأسطوانة والمخروط والكرة",
        "Coordinate geometry|الهندسة الإحداثية",
        "Scale drawings and bearings|الرسم بمقياس والاتجاهات",
        "Constructions with ruler and compass|الإنشاءات بالمسطرة والفرجار",
        "Circle theorems|نظريات الدائرة",
      ],
    },
  },
  {
    id: "data",
    title: "Data and Probability|البيانات والاحتمال",
    summary:
      "Collecting, showing and interpreting data, then measuring how likely things are.|جمع البيانات وعرضها وتفسيرها، ثم قياس احتمال وقوع الأحداث.",
    topics: {
      early: ["Sorting into groups|التصنيف إلى مجموعات", "Reading a picture graph|قراءة التمثيل بالصور"],
      lower: [
        "Tally charts|جداول العدّ",
        "Picture graphs|التمثيل بالصور",
        "Bar graphs|التمثيل بالأعمدة",
        "Comparing data|مقارنة البيانات",
      ],
      middle: [
        "Scaled bar graphs|الأعمدة ذات المقياس",
        "Line plots|التمثيل بالخط المنقّط",
        "Reading data tables|قراءة جداول البيانات",
        "Number and shape patterns|أنماط الأعداد والأشكال",
        "Line graphs over time|التمثيل بالخطوط عبر الزمن",
        "Interpreting graphs critically|قراءة الرسوم البيانية بوعي",
      ],
      upper: [
        "Mean, median, mode and range|المتوسط والوسيط والمنوال والمدى",
        "Histograms and box plots|المدرج التكراري والصندوق",
        "Probability of simple events|احتمال الأحداث البسيطة",
        "Tree diagrams and compound events|المخططات الشجرية والأحداث المركبة",
        "Scatter plots and correlation|الانتشار والارتباط",
        "Sampling and surveys|العينات والاستبانات",
        "Two-way tables|الجداول الثنائية",
        "Misleading statistics|الإحصاءات المضللة",
      ],
    },
  },
]);
